# Generated by Django 4.1.7 on 2023-02-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Команта чата', 'verbose_name_plural': 'Комнаты чатов'},
        ),
    ]
