# Generated by Django 4.1.7 on 2023-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Токен уведомления',
                'verbose_name_plural': 'Токены уведомлений',
            },
        ),
    ]
