# Generated by Django 4.1.7 on 2023-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtoken',
            name='token',
            field=models.TextField(unique=True, verbose_name='Токен'),
        ),
    ]
